version: '3.2'

services:
  node:
    build: ..
    container_name: 'learn_nestjs'
    ports:
      - 3003:3000

  postgresql:
    container_name: postgresql
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=p433word
      - POSTGRES_DB=nestjs_test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - dev_network

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   hostname: rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=root
  #     - RABBITMQ_DEFAULT_PASS=p433word
  #   volumes:
  #     - /var/lib/rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

  # redis:
  #   container_name: redis
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./redisdata/redis:/data"
  #   networks:
  #     - dev_network

networks:
  dev_network:
    driver: bridge

