version: '3.2'
networks:
  default:
    external: true
    name: dev_network

services:
  node:
    build: ..
    container_name: 'learn_nestjs'
    ports:
      - 3003:3000

  postgresql:
    container_name: postgresql
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=111111
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=111111
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  # redis:
  #   container_name: redis
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./redisdata/redis:/data"
  #   networks:
  #     - _network

